### ISSUE TITLE
angular support

### ISSUE THREAD

**Issue by avaulto** [scrtlabs/secret.js#6]
secretJS with simple angular 13 boilerplate producing a run time issue which prevents the app from running:

the log:
```

Error: node_modules/secretjs/dist/protobuf_stuff/tendermint/types/types.d.ts:1:8 - error TS1192: Module '"/Users/amircohen/development/arcane/node_modules/protobufjs/minimal"' has no default export.

1 import _m0 from "protobufjs/minimal";
         ~~~


Error: node_modules/secretjs/dist/protobuf_stuff/tendermint/types/validator.d.ts:1:8 - error TS1192: Module '"/Users/amircohen/development/arcane/node_modules/protobufjs/minimal"' has no default export.

1 import _m0 from "protobufjs/minimal";
         ~~~


Error: node_modules/secretjs/dist/protobuf_stuff/tendermint/version/types.d.ts:1:8 - error TS1192: Module '"/Users/amircohen/development/arcane/node_modules/protobufjs/minimal"' has no default export.

1 import _m0 from "protobufjs/minimal";
         ~~~

```

**Comment by avaulto** [comment]
fixed by adding custom webpack with the following 
    fallback: {
        // Here paste
        crypto: require.resolve("crypto-browserify"),
        stream: require.resolve("stream"),
        path : require.resolve("path-browserify")
      }

(need to install fallback packages)

**Comment by avaulto** [comment]
fixed by adding custom webpack config with: 

resolve: {
    fallback: {
        crypto: require.resolve("crypto-browserify"),
        stream: require.resolve("stream"),
        path : require.resolve("path-browserify")
      }
}

(need to install required packages)

**Comment by assafmo** [comment]
How can I generate the angular boilerplate, to test locally?  
I'll try to add these polyfills to secretjs itself. Webpack 5 is annoying. :unamused:

**Comment by assafmo** [comment]
Okay now this works:

```bash
git clone https://github.com/juanmesa2097/angular-boilerplate
cd angular-boilerplate
npm i -f secretjs@beta
npm run start
```

Please let me know if your setup is any different so I can debug it locally.

**Comment by avaulto** [comment]
You can simply generate new angular project with angular cli, install secretjs, run any fn from secretjs api and will see the issue

**Comment by assafmo** [comment]
Thanks, I managed to reproduce the issue, debugging now.

**Comment by assafmo** [comment]
@avaulto can you try now with the current `secretjs@beta`? :pray:

**Comment by avaulto** [comment]
@assafmo , seems like the webpack issue has been resolved!
but another problem poped =]


![image](https://user-images.githubusercontent.com/11775780/153749655-226adac1-4d4e-43c0-9294-154bc13f7a07.png)

and also in 
![image](https://user-images.githubusercontent.com/11775780/153749688-dd1fbeb2-c1a6-449b-bc8a-4390d5c168bc.png)
![image](https://user-images.githubusercontent.com/11775780/153749672-d8ea1b32-ceb3-4330-ba86-602151bcd7b7.png)

**Comment by assafmo** [comment]
Mmmm oh yeah it's now just `Wallet`. I'll fix the docs. :hand_over_mouth:

**Comment by assafmo** [comment]
Fixed: https://github.com/scrtlabs/secret.js#broadcasting-transactions

**Comment by avaulto** [comment]
@assafmo 
 create function still not working and new wallet constructor show error:
```
ERROR Error: Uncaught (in promise): TypeError: secretjs__WEBPACK_IMPORTED_MODULE_0__.Wallet is not a constructor
TypeError: secretjs__WEBPACK_IMPORTED_MODULE_0__.Wallet is not a constructor
```

**Comment by assafmo** [comment]
Yeah sorry for that, fixing once and for good...

**Comment by assafmo** [comment]
Try now?
